### ISSUE TITLE
Tutorials keep getting killed

### ISSUE THREAD

**Issue by txsrangers** [npm/how-to-npm#100] opened 2017-02-01 17:19 UTC
Challenge Name
https://www.freecodecamp.com/challenges/manage-packages-with-npm

Issue Description
When you get to the 8th tutorial in Cloud9, "Publish", when you press enter, all that happens is that "Killed" displays on the screen. I assumed that it was because they removed that tutorial from the program because I was able to run the 9th tutorial, BUT that was the only one I could run after #8. I was able to successfully complete 1-7, but 8 and 10-13 all just display "Killed" when you click on them.

Browser Information
Browser Name, Version: Chrome Version 55.0.2883.95 (64-bit)
Operating System: macOS Sierra
Mobile, Desktop, or Tablet: Mobile Macbook.

![screen shot 2017-02-01 at 10 48 19 am](https://cloud.githubusercontent.com/assets/20232282/22517883/4343de4a-e870-11e6-852f-5fdca8e8eece.png)
![screen shot 2017-02-01 at 10 48 42 am](https://cloud.githubusercontent.com/assets/20232282/22517888/461f5b1c-e870-11e6-9339-5abbe3668685.png)

**Comment by watilde** [comment] 2017-02-02 19:52
Hello!

I don't have any idea on it yet, then I will try to reproduce it on Cloud9. Before that, could you please give us the version of `Node.js` and `npm` you used? You can display them with the following commands:
```
node -v
npm -v
```

**Comment by watilde** [comment] 2017-02-02 19:58
I just tried on Cloud 9, and actually it worked.
![screen shot 2017-02-02 at 20 57 08](https://cloud.githubusercontent.com/assets/1716463/22565912/390f5ee8-e98a-11e6-8a3e-d15f0c2525f8.png)

Versions:
```
$ node -v
v4.6.1
$ npm -v
4.1.2
```

**Comment by txsrangers** [comment] 2017-02-02 20:00
$node -v
v. 4.6.1
$npm -v
4.1.2

**Comment by txsrangers** [comment] 2017-02-02 20:01
If I install a whole new lesson, it works for some reason, but I'm missing all my files if I do that, not to mention my completion status on all of the lessons.

**Comment by watilde** [comment] 2017-02-10 12:14
Hmm. Then can you try to update how-to-npm? Potentially, it's old version.
```
$ npm i -g how-to-npm
```

**Comment by watilde** [comment] 2017-03-13 13:26
Closing as resolved since there are no more reporters on here, but feel free to reopen this if you're still facing the error. Thanks!

**Closed as completed by watilde** 2017-03-13 13:26 UTC
Labels: question
