### ISSUE TITLE
Dist Tag commands give a 404 error

### ISSUE THREAD

**Issue by adamgcraig** [npm/how-to-npm#35] opened 2015-07-31 01:21 UTC
Everything works fine until I use what appears to be the correct command to add a dist tag.
Considering that I was able to use this command to add a dist tag to a module I created and published to the real npmjs.com using what I have learned from the tutorial up to this point, I am fairly confident that this is an issue with the dummy server set up for the tutorial and not with the command I entered.
Here is the text of npm-debug.log:
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'dist-tag',
1 verbose cli   'add',
1 verbose cli   'agc-retestpackage@0.0.1',
1 verbose cli   'useless' ]
2 info using npm@2.13.2
3 info using node@v0.12.7
4 verbose dist-tag add useless to agc-retestpackage@0.0.1
5 silly mapToRegistry name agc-retestpackage
6 silly mapToRegistry using default registry
7 silly mapToRegistry registry http://localhost:15443/
8 silly mapToRegistry uri http://localhost:15443/agc-retestpackage
9 verbose request uri http://localhost:15443/-/package/agc-retestpackage/dist-tags
10 verbose request no auth needed
11 info attempt registry request try #1 at 9:15:14 PM
12 verbose request id 875c22cbd3f2979b
13 http request GET http://localhost:15443/-/package/agc-retestpackage/dist-tags
14 http 404 http://localhost:15443/-/package/agc-retestpackage/dist-tags
15 verbose headers { 'content-type': 'application/json',
15 verbose headers   date: 'Fri, 31 Jul 2015 01:15:15 GMT',
15 verbose headers   connection: 'keep-alive',
15 verbose headers   'transfer-encoding': 'chunked' }
16 verbose stack Error: missing : -/package/agc-retestpackage/dist-tags
16 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:247:14)
16 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:170:14)
16 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:197:22)
16 verbose stack     at Request.emit (events.js:110:17)
16 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1050:14)
16 verbose stack     at Request.emit (events.js:129:20)
16 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:996:12)
16 verbose stack     at IncomingMessage.emit (events.js:129:20)
16 verbose stack     at _stream_readable.js:908:16
16 verbose stack     at process._tickCallback (node.js:355:11)
17 verbose statusCode 404
18 verbose cwd /Users/adamcraig/Sites/node_practice/how-to-npm2
19 error Darwin 14.4.0
20 error argv "node" "/usr/local/bin/npm" "dist-tag" "add" "agc-retestpackage@0.0.1" "useless"
21 error node v0.12.7
22 error npm  v2.13.2
23 error code E404
24 error 404 missing : -/package/agc-retestpackage/dist-tags
25 verbose exit [ 1, true ]

**Comment by claudiopro** [comment] 2015-09-12 21:17
This is a dupe of #21

**Comment by ashleygwilliams** [comment] 2015-10-21 21:16
closing for https://github.com/npm/how-to-npm/issues/45

**Closed as completed by ashleygwilliams** 2015-10-21 21:16 UTC
Labels: bug, duplicate, needs review
