### ISSUE TITLE
'c:\program' is not recognized as a command

### ISSUE THREAD

**Issue by ghsamm** [npm/how-to-npm#11] opened 2015-02-19 16:52 UTC
i'm using windows 7 and everything went well until i reach chapter 05 : LOGIN. it says the following

> > 'c:\Program' is not recognized as an internal or external command,
> > operable program or batch file.
> > 
> > Uh oh!
> > It looks like something went wrong
> > ###### 
> > ### YOUR SOLUTION IS NOT CORRECT!
> > ###### 

i guess it's referring to my node installation folder('c:\program files\nodejs')
ps: this is not my first nodeschool workshop and this is the first time something similar comes up

**Comment by linclark** [comment] 2015-02-19 16:58
Yes, this is very likely related to the Windows path. Thanks for posting the issue, we'll have to look into it.

**Comment by sejoker** [comment] 2015-02-22 19:21
I have the same problem with chapter 5 as @ghsamm  has, but in addition I have failed validation of the first chapter ( I am also Windows 7 user):
verifying that npm is installed...
Uh oh!  npm had a problem! {"killed":false,"code":1,"signal":null}
'c:\Program' is not recognized as an internal or external command,
operable program or batch file.
#########################################

### YOUR SOLUTION IS NOT CORRECT!

#########################################

**Comment by jsjaimohan** [comment] 2015-02-25 17:42
Error is reproducible : same as ghsamm 's

**Comment by gitting** [comment] 2015-02-27 18:10
This seems to be related to [https://www.npmjs.com/package/which](https://www.npmjs.com/package/which) that returns escaped path to `node.exe`, but doesn't escape blanks. That is, it would be `C:\\Program Files\\nodejs\\node.exe` instead of `C:\\Program\ Files\\nodejs\\node.exe`.

As a temp fix one could edit problems' js files that have that "problem" and remove references to `which` and just assign `'npm'` to npm variable where `which.sync(...)` was used.

There's `where` command on windows similar to `which` on linux so maybe it'd make sense to get rid of `which` package altogether and use those instead.

### EDIT:

I looked a bit more into it and it doesn't seem `which` package problem. Somehow the `verify` causes windows `cmd.exe` with `/s` flag which causes the subsequent command interpretation to fail.

**Comment by ghsamm** [comment] 2015-02-28 21:55
thank you @gitting this is working just replace var 
npm = require('which').sync('npm')
with
var npm = "npm"

**Comment by No9** [comment] 2015-03-12 19:59
Should we convert this into a pull request as +5 folks had it tonight nodeschool dublin?

**Comment by rustybailey** [comment] 2015-03-18 21:11
Just wanted to add my +1 to this. Got this error on Windows 8. @ghsamm 's solution worked, but not doing a PR yet -- first I'm just curious why `require('which').sync('npm')` was there in the first place? Is there any harm in just using 'npm'?

**Comment by gitting** [comment] 2015-03-18 21:19
@rustybailey - good question, and I have wondered as well. At least in Windows, if `where` finds `npm` then `npm` can be used by itself and be found just the same. I would assume that Linux's `which` works the same way.

**Comment by ghost** [comment] 2015-03-23 21:28
+1 on Windows 8.1. Happening on all steps after '05 Login'.

Glad to see it has already been noted nonetheless!

**Comment by CKcaesar** [comment] 2015-04-19 21:28
verifying that npm is installed...
Uh oh!  npm had a problem! {"killed":false,"code":1,"signal":null,"cmd":"C:\Win
dows\system32\cmd.exe /s /c \"D:\Program Files\nodejs\npm.CMD --version\""}

'D:\Program' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
#########################################

### YOUR SOLUTION IS NOT CORRECT!

#########################################

same thing happens to me

**Comment by run-time** [comment] 2015-04-29 22:03
I hit this error running the very first `how-to-npm verify` command.

I decided to uninstall nodejs from the default location `C:\Program Files\nodejs`
Then install it to this location instead `C:\nodejs` 

Doing this got me a little further but the command still failed...
![image](https://cloud.githubusercontent.com/assets/1427350/7402234/d9744fc6-ee8f-11e4-96f8-40772ccbfc4a.png)

I looked at the proposed fix here...
https://github.com/npm/how-to-npm/pull/17/files

And manually made the following change to see if it would get me any further...
![image](https://cloud.githubusercontent.com/assets/1427350/7402312/682cc2ac-ee90-11e4-8f0f-b374b78ffc9a.png)

Making the change above got me past the first `how-to-npm verify` command...
![image](https://cloud.githubusercontent.com/assets/1427350/7402372/eb7031bc-ee90-11e4-92e6-384fd8f23b30.png)

Pardon the detailed response but us windows users need the most help.  People running into this error need `how-to-npm` the most!  :laughing:

**Comment by No9** [comment] 2015-04-30 00:24
Hey @isaacs @mmalecki @linclark with nodeschool Intl only a couple of weeks away any chance we can have https://github.com/npm/how-to-npm/pull/17 reviewed and pushed by someone from the 
"wombat distribution unit" ? :) 
Thanks

**Comment by pcgeek86** [comment] 2015-06-30 03:27
+1 same issue here. Running `how-to-npm` verify on Windows 10 Build 10130 inside of PowerShell 5.0. I'm a bit surprised that the issue hasn't been resolved after months of reported issues.

**Code needs to properly plan for spaces in filesystem paths.** :)

![2015-06-29 21_24_11-windows shell experience host](https://cloud.githubusercontent.com/assets/466713/8423392/a1ead0ac-1ea5-11e5-9111-175d8d6f7a7d.png)

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by jgbbarreiros** [comment] 2015-08-04 15:31
I think this was made to run on the Node.js command prompt. There it works fine for me.

**Comment by IanLawrence** [comment] 2015-08-05 17:45
@jgbbarreiros it only works if you run Node.js command prompt as Administrator user. If you do not you still get the error below
![screenshot 67](https://cloud.githubusercontent.com/assets/400731/9093012/0b996ba2-3b80-11e5-8f8c-1ecf2eeed80a.png)

**Comment by ashleygwilliams** [comment] 2015-10-21 15:16
related: #19 #32 #33 #17

**Comment by divo93** [comment] 2016-02-11 07:03
Getting the same error.

**Comment by cannelflow** [comment] 2016-02-12 14:43
i was also getting same error then tried this using nodejs cmd it worked

**Comment by nickpapasavvas** [comment] 2016-08-04 11:27
@run-time  Thank you for the solution I had the same problem (windows 10, npm 3.10.5) at the exercises 00, 02,07 and your solution worked for all of them. Thanks a lot!!

**Comment by sahil-lakhwani** [comment] 2016-08-06 14:41
@ghsamm Thank you for the solution.

**Comment by 8fdafs2** [comment] 2016-08-27 10:12
If you have the error you may try run 'how-to-npm' in 'Node.js command prompt'.

**Comment by watilde** [comment] 2017-02-18 16:40
#108 is shipeed as v2.4.1. Closing as resolved :)

**Closed as completed by watilde** 2017-02-18 16:40 UTC
Labels: bug, needs review, code, windows, PR attached

**Comment by jszabo98** [comment] 2022-06-06 16:26
Still a bug?  https://stackoverflow.com/questions/72518859/npx-isnt-working-on-powershell-or-cmd-even-using-the-right-file-types
