### ISSUE TITLE
cannot install module

### ISSUE THREAD

**Issue by iliu16** [npm/how-to-npm#30] opened 2015-07-02 22:01 UTC
Prints this error:
C:\Users\iliu\how-to-npm>npm install @linclark/pkg
npm WARN package.json @iliu/how-to-npm@1.0.0 No README data
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "node" "C:\Users\iliu\AppData\Roaming\npm\node_modules\npm\
\bin\npm-cli.js" "install" "@linclark/pkg"
npm ERR! node v0.12.5
npm ERR! npm  v2.12.0

npm ERR! undefined is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\iliu\how-to-npm\npm-debug.log

C:\Users\iliu\how-to-npm>

debug log

0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   'C:\Users\iliu\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '@linclark/pkg' ]
2 info using npm@2.12.0
3 info using node@v0.12.5
4 verbose install initial load of C:\Users\iliu\how-to-npm\package.json
5 warn package.json @iliu/how-to-npm@1.0.0 No README data
6 verbose installManyTop reading scoped package data from C:\Users\iliu\how-to-npm\node_modules\npm-debug.log\package.json
7 verbose readDependencies loading dependencies from C:\Users\iliu\how-to-npm\package.json
8 silly cache add args [ '@linclark/pkg', null ]
9 verbose cache add spec @linclark/pkg
10 silly cache add parsed spec { raw: '@linclark/pkg',
10 silly cache add   scope: '@linclark',
10 silly cache add   name: '@linclark/pkg',
10 silly cache add   rawSpec: '',
10 silly cache add   spec: '_',
10 silly cache add   type: 'range' }
11 silly addNamed @linclark/pkg@_
12 verbose addNamed "_" is a valid semver range for @linclark/pkg
13 silly addNameRange { name: '@linclark/pkg', range: '_', hasData: false }
14 silly mapToRegistry name @linclark/pkg
15 silly mapToRegistry scope (from package name) @linclark
16 verbose mapToRegistry no registry URL found in name for scope @linclark
17 silly mapToRegistry using default registry
18 silly mapToRegistry registry http://localhost:15443/
19 silly mapToRegistry uri http://localhost:15443/@linclark%2fpkg
20 verbose addNameRange registry:http://localhost:15443/@linclark%2fpkg not in flight; fetching
21 verbose request uri http://localhost:15443/@linclark%2fpkg
22 verbose request no auth needed
23 info attempt registry request try #1 at 2:57:49 PM
24 verbose request id 2efef41c2d77fc0b
25 http request GET http://localhost:15443/@linclark%2fpkg
26 http 200 http://localhost:15443/@linclark%2fpkg
27 silly get cb [ 200,
27 silly get   { 'content-length': '2403',
27 silly get     'content-type': 'application/json',
27 silly get     connection: 'close',
27 silly get     date: 'Thu, 02 Jul 2015 21:57:49 GMT' } ]
28 verbose get saving @linclark/pkg to C:\Users\iliu\AppData\Roaming\npm-cache\localhost_15443_40linclark_252fpkg.cache.json
29 verbose stack TypeError: undefined is not a function
29 verbose stack     at calculateOwner (C:\Users\iliu\AppData\Roaming\npm\node_modules\npm\lib\utils\correct-mkdir.js:37:24)
29 verbose stack     at C:\Users\iliu\AppData\Roaming\npm\node_modules\npm\lib\utils\correct-mkdir.js:23:22
29 verbose stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
30 verbose cwd C:\Users\iliu\how-to-npm
31 error Windows_NT 6.1.7601
32 error argv "node" "C:\Users\iliu\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install" "@linclark/pkg"
33 error node v0.12.5
34 error npm  v2.12.0
35 error undefined is not a function
36 error If you need help, you may report this error at:
36 error     https://github.com/npm/npm/issues
37 verbose exit [ 1, true ]

**Comment by ashleygwilliams** [comment] 2015-10-21 21:25
i believe this is a dupe of #31, there are several PRs with solutions. i'm working with those contributors on merging.

**Comment by watilde** [comment] 2017-02-18 16:43
#108 is shipped as v2.4.1. Closing as resolved :)

**Closed as completed by watilde** 2017-02-18 16:43 UTC
Labels: duplicate, needs review, windows, PR attached
